name: Ormolu Check

    on:
      push:
        branches: [ main ]
      pull_request:
        branches: [ main ]

    jobs:
      format-check:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: tweag/run-ormolu@v1
          with:
            ormolu-version: "0.7.4.0"
            ormolu-args: "--mode check"

